-- Deprecated: do not execute this file on a current CRM database.
--
-- It predates the migration-based security model and contains broad RLS policies
-- that would undo protections in supabase/migrations.
--
-- Apply the versioned files in supabase/migrations/ in filename order instead.
-- For an existing production project, the current hardening migration is:
--   20260722032327_crm_security_and_ui_hardening.sql
